[workspace]
resolver = "3"
members = [
	"sui/sui", "sui/sui_runner", "sui/asset_provider", "sui/stage_manager",
	"game"
]

[workspace.dependencies]
sui.path = "./sui/sui"
sui_runner.path = "./sui/sui_runner"
asset_provider.path = "./sui/asset_provider"
